non-empty args

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -53,13 +53,13 @@ jobs:
       if: success() || steps.check_coverage.outcome == 'failure'
       run: |
         baseSha=${{ github.event.pull_request.base.sha }}
-        if [ "$baseSha" ]; then strykerSince="--since:$baseSha"; fi
+        if [ "$baseSha" ]; then endArgs="-V Error --since:$baseSha"; else endArgs="-V Error"; fi
         returncode=0
         shopt -s extglob globstar
         for testproj in *.+(Test*(s)|UnitTest*(s)); do
           echo "Generating mutants for: $testproj..."
-          #iterr=$(dotnet stryker -tp "$testproj" $strykerSince &>/dev/null; echo $?)
-          iterr=$(dotnet stryker -tp "$testproj" $strykerSince; echo $?)
+          #iterr=$(dotnet stryker -tp "$testproj" "$endArgs" &>/dev/null; echo $?)
+          iterr=$(dotnet stryker -tp "$testproj" "$endArgs"; echo $?)
           [ $iterr != 0 ] && echo " -- failed to destroy all mutants :(" && returncode=1
           [ $iterr == 0 ] && echo " -- you destroyed all the mutants :)"
           echo " -- staging report to artifact location..."
